fix(chart): make rbac more explicit
ionos-cloud/uptrends-operator pull request #60
Opened 2023-08-09 09:36 UTC by pborn-ionos

2023-08-09 09:46 UTC, mcbenjemaa requested changes

2023-08-09 09:46 UTC, mcbenjemaa commented on charts/uptrends/templates/cluster_role.yaml
> +  - uptrends
please add status sub resource and finalizer

2023-08-09 09:46 UTC, mcbenjemaa commented on charts/uptrends/templates/cluster_role.yaml
> +  - get
we need delete verb also, as part of the ingress deleted event.

2023-08-10 06:59 UTC, pborn-ionos commented on charts/uptrends/templates/cluster_role.yaml
> +  - get
Good catch. Updated.

2023-08-10 08:01 UTC, pborn-ionos commented on charts/uptrends/templates/cluster_role.yaml
> +  - uptrends
Updated as discussed.

2023-08-10 08:12 UTC, mcbenjemaa approved these changes
LGTM

2023-08-10 09:31 UTC, merged